"use client";

import { useEffect } from "react";
import Link from "next/link";
import Image from "next/image";
import { useLanguage } from "@/lib/language-context";
import { useEventsQueue } from "@/lib/events-queue-context";
import { Header } from "../components/header";

// ── Real demo assets (generated by scripts/generate-demo.ts) ────────────
const DEMO = {
  screenshots: [
    { src: "/demo/clubgg/screenshots/step_1_ya4leyew.png", he: "הורדת האפליקציה", en: "Download App" },
    { src: "/demo/clubgg/screenshots/step_2_zrre6dxy.png", he: "יצירת חשבון", en: "Create Account" },
    { src: "/demo/clubgg/screenshots/step_3_vn1yknj7.png", he: "מציאת המועדון", en: "Find Club" },
    { src: "/demo/clubgg/screenshots/step_4_0m54l55g.png", he: "הזנת Club ID", en: "Enter Club ID" },
    { src: "/demo/clubgg/screenshots/step_5_ae34qyn4.png", he: "הצטרפות למועדון", en: "Join Club" },
    { src: "/demo/clubgg/screenshots/step_6_3d4bbc3l.png", he: "אתם בפנים!", en: "You're In!" },
  ],
  demoPage: "/demo/clubgg/videos/index.html",
  pdf: "/demo/clubgg/docs/Aces_High_-_ClubGG_2026-03-09T19-54-12.pdf",
  clubName: "Aces High",
  clubId: "827364",
  platform: "ClubGG",
  stepCount: 6,
};

// ── WhatsApp contact — REPLACE with your real number ────────────────────
const WHATSAPP_NUMBER = "972523227765";
const WHATSAPP_LINK = `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent("היי, ראיתי את ExplainIt ואני מעוניין לייצר הסבר למועדון שלי")}`;

const PLATFORMS = [
  { name: "ClubGG", color: "from-blue-500 to-blue-700", icon: "CG" },
  { name: "PPPoker", color: "from-red-500 to-red-700", icon: "PP" },
  { name: "PokerBros", color: "from-green-500 to-green-700", icon: "PB" },
];

const HOW_STEPS = [
  { he: "תגיד מה האפליקציה", en: "Name your platform", descHe: "ClubGG? PPPoker? PokerBros?", descEn: "ClubGG? PPPoker? PokerBros?" },
  { he: "תמלא Club ID ושם", en: "Enter Club ID & name", descHe: "שניות. זה הכל.", descEn: "Seconds. That's it." },
  { he: "המערכת מייצרת הכל", en: "System generates everything", descHe: "סרטון + PDF + דף דמו. אוטומטי.", descEn: "Video + PDF + demo page. Automatic." },
  { he: "תשלח לשחקנים", en: "Share with players", descHe: "ישר לוואטסאפ בלחיצה.", descEn: "Straight to WhatsApp in one click." },
];

export default function PokerLandingPage() {
  const { isHe } = useLanguage();
  const trackEvent = useEventsQueue();

  useEffect(() => {
    trackEvent({ type: "poker_page_view" });
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  return (
    <div className="min-h-screen bg-[#0a0a1a]">
      <Header />

      {/* ── Hero ──────────────────────────────────────────────────── */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-b from-indigo-900/20 to-transparent" />
        <div className="relative max-w-5xl mx-auto px-4 pt-16 pb-20 text-center">
          <div className="inline-flex items-center gap-2 bg-white/5 border border-white/10 rounded-full px-4 py-1.5 mb-6">
            <span className="w-2 h-2 bg-green-400 rounded-full animate-pulse" />
            <span className="text-xs text-white/60">
              ClubGG / PPPoker / PokerBros
            </span>
          </div>

          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold text-white leading-tight mb-6">
            {isHe ? (
              <>
                תפסיק להסביר לשחקנים
                <br />
                <span className="bg-gradient-to-r from-indigo-400 to-amber-400 bg-clip-text text-transparent">
                  איך להצטרף למועדון
                </span>
              </>
            ) : (
              <>
                Stop explaining to players
                <br />
                <span className="bg-gradient-to-r from-indigo-400 to-amber-400 bg-clip-text text-transparent">
                  how to join your club
                </span>
              </>
            )}
          </h1>

          <p className="text-lg sm:text-xl text-white/50 max-w-2xl mx-auto mb-10 leading-relaxed">
            {isHe
              ? "תייצר סרטון הסבר מקצועי + PDF מודפס בדקות. תשלח ישר לוואטסאפ. בלי עורך וידאו, בלי להסביר מאפס כל פעם מחדש."
              : "Generate a professional explainer video + printed PDF in minutes. Share directly to WhatsApp. No video editor, no repeating yourself."}
          </p>

          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              href="/editor?platform=clubgg"
              onClick={() => trackEvent({ type: "poker_cta_click", payload: { target: "hero_create" } })}
              className="bg-gradient-to-r from-indigo-600 to-indigo-500 text-white font-bold text-lg px-8 py-4 rounded-xl hover:shadow-lg hover:shadow-indigo-500/25 transition-all active:scale-[0.98]"
            >
              {isHe ? "תייצר הסבר עכשיו — חינם" : "Create Explainer Now — Free"}
            </Link>
            <a
              href="#proof"
              onClick={() => trackEvent({ type: "poker_cta_click", payload: { target: "see_example" } })}
              className="bg-white/5 hover:bg-white/10 text-white/70 hover:text-white font-semibold text-lg px-8 py-4 rounded-xl transition-all"
            >
              {isHe ? "תראה דוגמה אמיתית" : "See a real example"}
            </a>
          </div>

          {/* Platform logos */}
          <div className="flex justify-center gap-4 mt-12">
            {PLATFORMS.map((p) => (
              <div
                key={p.name}
                className={`w-16 h-16 rounded-2xl bg-gradient-to-br ${p.color} flex items-center justify-center text-white font-bold text-sm shadow-lg`}
              >
                {p.icon}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Pain ──────────────────────────────────────────────────── */}
      <section className="py-14 px-4 border-t border-white/5">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-2xl sm:text-3xl font-bold text-white text-center mb-8">
            {isHe ? "מכיר את זה?" : "Sound familiar?"}
          </h2>
          <div className="grid sm:grid-cols-2 gap-4">
            {[
              isHe ? "שחקן חדש שואל איך להוריד את האפליקציה — בפעם העשירית השבוע" : "New player asks how to download the app — for the 10th time this week",
              isHe ? "אתה מצלם מסך, מסמן חיצים, שולח 8 הודעות — ובסוף הוא עדיין לא מבין" : "You screenshot, draw arrows, send 8 messages — and they still don't get it",
              isHe ? "שחקנים רוצים להצטרף אבל Club ID לא ברור להם" : "Players want to join but Club ID confuses them",
              isHe ? "אתה מבזבז שעות על הסברים במקום לנהל משחקים" : "You waste hours on explanations instead of running games",
            ].map((pain, i) => (
              <div key={i} className="bg-red-500/5 border border-red-500/10 rounded-xl p-4 flex items-start gap-3">
                <span className="text-red-400 text-lg shrink-0 mt-0.5">x</span>
                <p className="text-white/70 text-sm">{pain}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── REAL Proof Section ────────────────────────────────────── */}
      <section id="proof" className="py-16 px-4 bg-gradient-to-b from-indigo-900/10 to-transparent border-t border-white/5">
        <div className="max-w-5xl mx-auto">
          {/* Heading */}
          <div className="text-center mb-4">
            <div className="inline-flex items-center gap-2 bg-green-500/10 border border-green-500/20 rounded-full px-4 py-1.5 mb-4">
              <span className="w-2 h-2 bg-green-400 rounded-full" />
              <span className="text-xs text-green-400 font-medium">
                {isHe ? "פלט אמיתי מהמערכת" : "Real system output"}
              </span>
            </div>
            <h2 className="text-2xl sm:text-3xl font-bold text-white">
              {isHe
                ? "הנה הסבר אמיתי שנוצר ב-2 דקות"
                : "Here's a real explainer generated in 2 minutes"}
            </h2>
            <p className="text-white/40 mt-2 text-sm">
              {isHe
                ? `נוצר למועדון "${DEMO.clubName}" (Club ID: ${DEMO.clubId}) • ${DEMO.stepCount} שלבים • עברית • ${DEMO.platform}`
                : `Generated for club "${DEMO.clubName}" (Club ID: ${DEMO.clubId}) • ${DEMO.stepCount} steps • Hebrew • ${DEMO.platform}`}
            </p>
          </div>

          {/* Screenshot strip — real Playwright screenshots */}
          <div className="mt-10 overflow-x-auto pb-4 -mx-4 px-4">
            <div className="flex gap-4 min-w-max">
              {DEMO.screenshots.map((shot, i) => (
                <div key={i} className="w-[180px] shrink-0">
                  <div className="relative rounded-xl overflow-hidden border border-white/10 bg-[#0f0f1a] shadow-lg">
                    <div className="absolute top-2 left-2 z-10 w-6 h-6 rounded-full bg-indigo-600 flex items-center justify-center text-white text-xs font-bold">
                      {i + 1}
                    </div>
                    <Image
                      src={shot.src}
                      alt={isHe ? shot.he : shot.en}
                      width={400}
                      height={780}
                      className="w-full h-auto"
                      unoptimized
                    />
                  </div>
                  <p className="text-white/50 text-xs text-center mt-2 font-medium">
                    {isHe ? shot.he : shot.en}
                  </p>
                </div>
              ))}
            </div>
          </div>

          {/* Output CTAs — video demo + PDF + try free */}
          <div className="grid sm:grid-cols-3 gap-4 mt-10">
            {/* Live Demo */}
            <a
              href={DEMO.demoPage}
              target="_blank"
              rel="noopener noreferrer"
              onClick={() => trackEvent({ type: "poker_cta_click", payload: { target: "demo_video" } })}
              className="group bg-white/[0.04] border border-white/10 rounded-xl p-5 hover:border-indigo-500/30 transition flex items-start gap-4"
            >
              <div className="w-10 h-10 rounded-lg bg-indigo-500/10 flex items-center justify-center text-indigo-400 shrink-0 group-hover:bg-indigo-500/20 transition">
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M15.91 11.672a.375.375 0 010 .656l-5.603 3.113a.375.375 0 01-.557-.328V8.887c0-.286.307-.466.557-.327l5.603 3.112z" />
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
              </div>
              <div>
                <h3 className="text-white font-semibold text-sm">
                  {isHe ? "צפה בסרטוני ההסבר" : "Watch Explainer Videos"}
                </h3>
                <p className="text-white/40 text-xs mt-1">
                  {isHe ? "6 סרטונים מונפשים + סקירה כללית" : "6 animated videos + overview"}
                </p>
              </div>
            </a>

            {/* PDF */}
            <a
              href={DEMO.pdf}
              target="_blank"
              rel="noopener noreferrer"
              onClick={() => trackEvent({ type: "poker_cta_click", payload: { target: "demo_pdf" } })}
              className="group bg-white/[0.04] border border-white/10 rounded-xl p-5 hover:border-red-500/30 transition flex items-start gap-4"
            >
              <div className="w-10 h-10 rounded-lg bg-red-500/10 flex items-center justify-center text-red-400 shrink-0 group-hover:bg-red-500/20 transition">
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m2.25 0H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" />
                </svg>
              </div>
              <div>
                <h3 className="text-white font-semibold text-sm">
                  {isHe ? "הורד PDF מודפס" : "Download Printable PDF"}
                </h3>
                <p className="text-white/40 text-xs mt-1">
                  {isHe ? "9 עמודים, צילומי מסך, מספור שלבים" : "9 pages, screenshots, numbered steps"}
                </p>
              </div>
            </a>

            {/* Try Free */}
            <Link
              href="/editor?platform=clubgg"
              onClick={() => trackEvent({ type: "poker_cta_click", payload: { target: "try_free" } })}
              className="group bg-gradient-to-r from-indigo-600/10 to-indigo-500/10 border border-indigo-500/20 rounded-xl p-5 hover:border-indigo-500/40 transition flex items-start gap-4"
            >
              <div className="w-10 h-10 rounded-lg bg-indigo-500/20 flex items-center justify-center text-indigo-400 shrink-0 group-hover:bg-indigo-500/30 transition">
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 4.5v15m7.5-7.5h-15" />
                </svg>
              </div>
              <div>
                <h3 className="text-white font-semibold text-sm">
                  {isHe ? "תייצר אחד למועדון שלך" : "Make One for Your Club"}
                </h3>
                <p className="text-white/40 text-xs mt-1">
                  {isHe ? "חינם, בלי כרטיס אשראי" : "Free, no credit card needed"}
                </p>
              </div>
            </Link>
          </div>
        </div>
      </section>

      {/* ── How It Works ──────────────────────────────────────────── */}
      <section id="how" className="py-14 px-4 bg-white/[0.02]">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-2xl sm:text-3xl font-bold text-white text-center mb-10">
            {isHe ? "4 שלבים. דקות בודדות." : "4 steps. Minutes."}
          </h2>
          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {HOW_STEPS.map((step, i) => (
              <div key={i} className="text-center">
                <div className="w-12 h-12 rounded-full bg-indigo-600 flex items-center justify-center text-white font-bold text-xl mx-auto mb-4">
                  {i + 1}
                </div>
                <h3 className="text-white font-semibold mb-2">{isHe ? step.he : step.en}</h3>
                <p className="text-white/40 text-sm">{isHe ? step.descHe : step.descEn}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Platforms ─────────────────────────────────────────────── */}
      <section className="py-14 px-4 border-t border-white/5">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-2xl sm:text-3xl font-bold text-white text-center mb-4">
            {isHe ? "עובד עם כל הפלטפורמות" : "Works with all platforms"}
          </h2>
          <p className="text-white/40 text-center mb-8">
            {isHe
              ? "תבחר את הפלטפורמה — המערכת יודעת בדיוק מה להסביר"
              : "Choose your platform — the system knows exactly what to explain"}
          </p>
          <div className="grid sm:grid-cols-3 gap-6">
            {PLATFORMS.map((p) => (
              <Link
                key={p.name}
                href={`/editor?platform=${p.name.toLowerCase()}`}
                onClick={() => trackEvent({ type: "poker_cta_click", payload: { target: "platform_card", platform: p.name } })}
                className="bg-white/[0.03] border border-white/5 rounded-2xl p-6 text-center hover:border-indigo-500/20 transition group"
              >
                <div className={`w-14 h-14 rounded-xl bg-gradient-to-br ${p.color} flex items-center justify-center text-white font-bold text-lg mx-auto mb-4`}>
                  {p.icon}
                </div>
                <h3 className="text-white font-bold text-lg mb-2">{p.name}</h3>
                <p className="text-white/40 text-sm">
                  {isHe
                    ? "הורדה, הרשמה, Club ID, הצטרפות — הכל אוטומטי"
                    : "Download, signup, Club ID, join — all automatic"}
                </p>
                <span className="inline-block mt-3 text-xs text-indigo-400 group-hover:text-indigo-300 transition">
                  {isHe ? "תייצר הסבר →" : "Create explainer →"}
                </span>
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* ── FAQ ───────────────────────────────────────────────────── */}
      <section className="py-14 px-4 bg-white/[0.02]">
        <div className="max-w-3xl mx-auto">
          <h2 className="text-2xl font-bold text-white text-center mb-8">
            {isHe ? "שאלות שמפעילים שואלים" : "Questions operators ask"}
          </h2>
          <div className="space-y-4">
            {[
              {
                q: isHe ? "זה לוקח הרבה זמן?" : "Does it take long?",
                a: isHe ? "דקות בודדות. ממלאים פרטים, המערכת עושה את השאר." : "Minutes. Fill in details, the system does the rest.",
              },
              {
                q: isHe ? "צריך לדעת לערוך וידאו?" : "Do I need video editing skills?",
                a: isHe ? "בכלל לא. הסרטונים נוצרים אוטומטית. אפס עריכה." : "Not at all. Videos are generated automatically. Zero editing.",
              },
              {
                q: isHe ? "השחקנים שלי ידעו להשתמש בזה?" : "Will my players understand this?",
                a: isHe ? "הם מקבלים סרטון הסבר או PDF — צעד אחר צעד, בעברית. מותאם לפלטפורמה שלהם." : "They get an explainer video or PDF — step by step, localized. Matched to their platform.",
              },
              {
                q: isHe ? "כמה זה עולה?" : "How much does it cost?",
                a: isHe ? "הראשון חינם לגמרי, בלי כרטיס אשראי. אח\"כ $29/חודש ללא הגבלה." : "First one completely free, no credit card. Then $29/month unlimited.",
              },
            ].map((faq, i) => (
              <div key={i} className="bg-white/[0.03] border border-white/5 rounded-xl p-5">
                <h3 className="text-white font-semibold mb-2">{faq.q}</h3>
                <p className="text-white/50 text-sm">{faq.a}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Final CTA ─────────────────────────────────────────────── */}
      <section className="py-16 px-4 border-t border-white/5">
        <div className="max-w-3xl mx-auto text-center">
          <h2 className="text-3xl sm:text-4xl font-extrabold text-white mb-4">
            {isHe ? "מוכן להפסיק להסביר?" : "Ready to stop explaining?"}
          </h2>
          <p className="text-white/50 text-lg mb-8">
            {isHe
              ? "הראשון עלינו — בלי כרטיס אשראי. תייצר, תשלח, תחסוך שעות."
              : "First one's on us — no credit card. Generate, share, save hours."}
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center mb-6">
            <Link
              href="/editor?platform=clubgg"
              onClick={() => trackEvent({ type: "poker_cta_click", payload: { target: "final_create" } })}
              className="bg-gradient-to-r from-indigo-600 to-indigo-500 text-white font-bold text-lg px-8 py-4 rounded-xl hover:shadow-lg hover:shadow-indigo-500/25 transition-all active:scale-[0.98]"
            >
              {isHe ? "תייצר הסבר חינם עכשיו" : "Create Free Explainer Now"}
            </Link>
            <Link
              href="/pricing"
              onClick={() => trackEvent({ type: "poker_cta_click", payload: { target: "view_plans" } })}
              className="bg-white/5 hover:bg-white/10 text-white/70 hover:text-white font-semibold text-lg px-8 py-4 rounded-xl transition-all"
            >
              {isHe ? "צפה בתוכניות" : "View Plans"}
            </Link>
          </div>

          {/* WhatsApp direct contact */}
          <div className="flex items-center justify-center gap-2 mt-4">
            <a
              href={WHATSAPP_LINK}
              target="_blank"
              rel="noopener noreferrer"
              onClick={() => trackEvent({ type: "poker_cta_click", payload: { target: "whatsapp_contact" } })}
              className="inline-flex items-center gap-2 text-sm text-green-400 hover:text-green-300 transition"
            >
              <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
                <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z" />
              </svg>
              {isHe ? "שלח לנו הודעה בוואטסאפ" : "Message us on WhatsApp"}
            </a>
          </div>
        </div>
      </section>

      {/* ── Footer ────────────────────────────────────────────────── */}
      <footer className="border-t border-white/5 px-4 py-6">
        <div className="max-w-5xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-3 text-xs text-white/20">
          <span>ExplainIt v1.0</span>
          <div className="flex gap-4">
            <Link href="/" className="hover:text-white/40 transition">{isHe ? "דף הבית" : "Home"}</Link>
            <Link href="/editor" className="hover:text-white/40 transition">Smart Mode</Link>
            <Link href="/results" className="hover:text-white/40 transition">{isHe ? "תוצאות" : "Results"}</Link>
            <a href={WHATSAPP_LINK} target="_blank" rel="noopener noreferrer" className="hover:text-green-400/60 transition">WhatsApp</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
